spring:
  profiles:
    active: @profiles.active@

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.li98.blog.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    cn.li98.blog: debug
  file:
    name: blog-log/log-dev

# 请填入注册后得到的accessKey和accessSecretKey
qiniu:
  accessKey: xxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  accessSecretKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx_xxxxx
  bucketName: cn-blog-li98
  domainName: http://rldb7nvd2.hb-bkt.clouddn.com/


