server:
  port: 8080
  address: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qblog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .html
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.li98.blog.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    cn.li98.blog: debug
  file:
    name: blog-log/log-dev

qiniu:
  accessKey: HFc4f-7Q0Ct48SRdGBGIM5TJ7Ij1NEjSwgyIqMWf
  accessSecretKey: FykyjvQC0mronnpBhaymnK3wjDSM3_a8fvrPRZHN
  bucketName: cn-blog-li98
  domainName: http://rldb7nvd2.hb-bkt.clouddn.com/

files:
  upload:
    path: D:\WorkSpace\IDEA\QBlogBackend\src\main\resources\files\
