server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/qblog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: xxxx
    password: xxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .html
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    root: info
    cn.li98.blog: debug
  file:
    name: log-prod/log-prod

files:
  upload:
    path: files/