spring:
  profiles:
    active: prod

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.li98.blog.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 请填入注册后得到的accessKey和accessSecretKey
qiniu:
  accessKey: xxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  accessSecretKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  bucketName: cn-blog-li98
  domainName: http://rldb7nvd2.hb-bkt.clouddn.com/


