server:
  port: 8080
  address: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qblog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .html
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cn.li98.blog.dao

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

blog:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: Authorization

logging:
  level:
    root: info
    cn.li98.blog: debug
  file:
    name: blog-log/log-dev

qiniu:
  accessKey: HFc4f-7Q0Ct48SRdGBGIM5TJ7Ij1NEjSwgyIqMWf
  accessSecretKey: FykyjvQC0mronnpBhaymnK3wjDSM3_a8fvrPRZHN
  bucketName: cn-blog-li98
  domainName: http://rldb7nvd2.hb-bkt.clouddn.com/